server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg_db_test
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate #validate #create-drop #update #create #none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
#    create-schemas: true
#    url: jdbc:postgresql://postgres:5432/pg_db_test
#    user: postgres
#    password: pass

